backend:
  name: github
  repo: funkycrash/photo-album-of-life
  branch: master
media_folder: assets/img/uploads
collections:
  - name: 'destination' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Destination' # Used in the UI, ie.: "New Post"
    folder: '_destination' # The path to the folder where the documents are stored
    sort: 'date:desc' # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: '{{year}}-{{month}}-{{slug}}'
    fields: # The fields each document in this collection have
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'destination' }
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - { label: 'Date', name: 'date', widget: 'datetime', format: 'YYYY-MM' }
      - { label: 'Featured Image', name: 'featuredImage', widget: 'image', default: '/assets/img/uploads/morocco.jpg' }
      - { label: 'Intro Paragraph', name: 'intro_paragraph', widget: 'markdown', required: false }
      - { label: 'Places', name: 'places', widget: 'map', required: false }
      - { label: 'Our take', name: 'carlyTake', widget: 'markdown', required: false }
      - {
          label: 'Gallery',
          name: 'gallery',
          widget: 'image',
          default: '/uploads/chocolate-dogecoin.jpg',
          media_library: { config: { multiple: true } },
        }
