backend:
  name: github
  repo: funkycrash/photo-album-of-life
  branch: master
media_folder: assets/img/uploads
collections:
  - name: 'destination' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Destination' # Used in the UI, ie.: "New Post"
    folder: '_destination' # The path to the folder where the documents are stored
    sort: 'dateFrom:asc' # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: '{{year}}-{{dateFrom}}-{{slug}}'
    fields: # The fields each document in this collection have
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'destination' }
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - { label: 'Date From', name: 'dateFrom', widget: 'datetime', format: 'YYYY-MM' }
      - { label: 'Date To', name: 'dateTo', widget: 'datetime', format: 'YYYY-MM' }
      - { label: 'Featured Image', name: 'featuredImage', widget: 'image', default: '/assets/img/uploads/morocco.jpg' }
      - { label: 'Intro Paragraph', name: 'intro_paragraph', widget: 'markdown', required: false }
      - { label: 'Places', name: 'places', widget: 'map', required: false }
      - { label: 'Our take', name: 'ourTake', widget: 'markdown', required: false }
      - { label: 'Gallery', name: 'gallery0', widget: 'image', required: false }
      - { label: 'Gallery', name: 'gallery1', widget: 'image', required: false }
      - { label: 'Gallery', name: 'gallery2', widget: 'image', required: false }
      - { label: 'Gallery', name: 'gallery3', widget: 'image', required: false }
      - { label: 'Gallery', name: 'gallery4', widget: 'image', required: false }
      - { label: 'Gallery', name: 'gallery5', widget: 'image', required: false }
      - { label: 'Gallery', name: 'gallery6', widget: 'image', required: false }
      - { label: 'Gallery', name: 'gallery7', widget: 'image', required: false }
      - { label: 'Gallery', name: 'gallery8', widget: 'image', required: false }
